### ISSUE TITLE
missed argument in redisCommand SISMEMBER call

### ISSUE THREAD

**Issue by dumbuzz** [nahanni/rw_redis_fdw#12]
Wrong line:
rctx->r_reply = redisCommand(ctx, "SISMEMBER %s",rctx->pfxkey, rctx->where_conds.s_value);
Correct line should be:
rctx->r_reply = redisCommand(ctx, "SISMEMBER %s **%s**", rctx->pfxkey, rctx->where_conds.s_value);

Due to this error, I again caught segfault of master postgres process(

**Comment by l-d-x** [comment]
thanks for catching it.

**Comment by dumbuzz** [comment]
Offtop - do you have plans for upgrading to support postgresql 9.6? there are some api changes in fdw-functions in 9.6

**Comment by l-d-x** [comment]
yes, I'm going to invest some time into seeing what's different in 9.6 and update it from there.

**Comment by l-d-x** [comment]
ok, was a simple change. It should work with 9.6 now.

**Comment by dumbuzz** [comment]
Sorry, could not test, cause I have no 9.6 setup yet. But I think you missed some api changes.
Look at this commit https://github.com/pg-redis-fdw/redis_fdw/commit/185999e50b340055a96259f3b8bac89c9baecba4
There is also change in redisGetForeignPlan too.

**Comment by l-d-x** [comment]
All covered in the current commit; otherwise it would fail the build. That reference commit from redis_fdw is for 9.5 which was supported here quite a while ago.

The only change in 9.6 was the `create_foreignscan_path()` function which needed a PathTarget argument.

**Comment by dumbuzz** [comment]
Oh, yes, sorry....didn't notice that other changes was for 9.5.
I'll try to test 9.6 as soon as possible and report results here.

**Comment by dumbuzz** [comment]
I've recently test on 9.6 - everything OK.
