### ISSUE TITLE
Compatibility with PostgreSQL10.x

### ISSUE THREAD

**Issue by GHNewbiee** [nahanni/rw_redis_fdw#13]
Hi,

I tried to compile the extension for pg10.x and I got the following error:

```
redis_fdw.c:2499:12: error: too many arguments to function ‘ExecEvalExpr’
    datum = ExecEvalExpr(expr_state, econtext,&is_null, NULL);
            ^
In file included from /usr/include/postgresql/10/server/funcapi.h:22:0,
                 from redis_fdw.c:43:
/usr/include/postgresql/10/server/executor/executor.h:285:1: note: declared here
 ExecEvalExpr(ExprState *state,
```

So, I removed the last argument (NULL) and compiled it successfully.

Because I am **not** an experienced user, I would like to ask if I take any **great risk** to damage the DB by keeping on using the extension with pg10.x.

Tia

**Comment by l-d-x** [comment]
It looks like pgsql 10 does not require the last parameter. I'll need to make another case for version 10 API.

**Comment by GHNewbiee** [comment]
I think that removing the last parameter is **not** enough.

I can run **any** statement only for the **first 5 times**. After that (6th time) an **error** always appears: `KEY is NULL` (redis_fdw.c @ line: 2571).

Does it have to do with `argvlen[0] = 5;` in line 730?

Tia

**Comment by l-d-x** [comment]
L:730 is let pgsql know the length of the argument's string.

The key is required to make a query for a hash table, aka hmget. Not sure what's going on. Do you have your table schema and query string that you're trying to use?

**Comment by GHNewbiee** [comment]
I have used a similar schema to yours:

```
CREATE FOREIGN TABLE rft_str(
      key    TEXT,
      value  TEXT,
      expiry INT
  ) SERVER xxx
    OPTIONS (tabletype 'string', database '0');
```
only the table and server names I have changed, and the queries are very simple `INSERT` or `SELECT` types. As I have already written, only the **first 5 any** statements run without problem. From the 6th one the error appears. When I use a function I have to REPLACE it in order I can execute another 5 statements, and go on...

For the time being I use the following manner:
```
         postgres_fdw           redis_fdw
Pg10.5  <------------>  Pg9.6  <--------->  Redis
```
which works fine, free of any trouble.

Tia

**Comment by l-d-x** [comment]
I ran a test on Ubuntu 18 with many insertions and queries it didn't hit your issue. This is with PostgreSQL 10.5 and Redis 4. There might be something else that's causing problems in your setup.

```
CREATE EXTENSION redis_fdw;

CREATE SERVER redis_server FOREIGN DATA WRAPPER redis_fdw OPTIONS (host '127.0.0.1', port '6379');

CREATE FOREIGN TABLE rft_str (
  key TEXT
  value TEXT,
  expiry INT
) SERVER redis_server OPTIONS(tabletype 'string', database '0');

# many insertions after
INSERT INTO rft_str(key, value) values('k1', 'v1');
...
```

**Comment by GHNewbiee** [comment]
Hi,

Please add expiry values to your multiple inserts, and let me know the
result. I have only tested with expiry values being included.

Tia<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table
style="border-top: 1px solid #D3D4DE;">
	<tr>
      <td style="width: 55px; padding-top: 18px;"><a
href="http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-green-avg-v1.png"
alt="" width="46" height="29" style="width: 46px; height: 29px;"
/></a></td>
		<td style="width: 470px; padding-top: 17px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Libre de virus. <a
href="http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avg.com</a> 		</td>
	</tr>
</table>
<a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

**Comment by l-d-x** [comment]
I've just tested it with expiry in the insertion and am not encountering the issue. There's got to be something else going on that could be corrupting your module. I'm going to apply the change to enable support for PostgreSQL 10.

**Comment by GHNewbiee** [comment]
Great! Tal for your time and sorry for any inconvenience.
