### ISSUE TITLE
redis "KEYS *" command?

### ISSUE THREAD

**Issue by josmac69** [nahanni/rw_redis_fdw#4]
Hi. I tested your fdw and it is really really good.
Only thing I was not able to simulate is redis " KEYS * " command which gives me list of existing keys.
Or KEYS "key-name*" which would be extremaly helpful.
Would it be possible to implement it somehow?
Maybe in similar way like LEN command...
Thanks.

**Comment by l-d-x** [comment]
I will take a look at implementing this. It isn't particularly difficult; I didn't implement it originally because the key space could be particularly large with the various data types involved.

**Comment by schinckel** [comment]
It's also worth pointing out that `KEYS *` is generally not a good idea: it can really bring your redis server to it's knees.

**Comment by josmac69** [comment]
Yes, you are right. But we have use case for this and data volume is not that big. 
Cheers

**Comment by l-d-x** [comment]
Commit https://github.com/nahanni/rw_redis_fdw/commit/0e039f4b0ef565e1d4114228199076295a15ead1
